Fix build on OpenBSD
On OpenBSD (and maybe elsewhere?), stdio.h has the following macros:

    #define stdin   (&__sF[0])
    #define stdout  (&__sF[1])
    #define stderr  (&__sF[2])

which causes the following compilation errors on
child_processes-platform-binding.c:

    In file included from child_processes-platform-binding.c:49:
    child_processes-platform-binding.c:82:23: error: expected ')' before
    '&' token
       82 |  pid_t * pid,  int  * stdin, int  * stdout, int * stderr)
          |                       ^~~~~
    child_processes-platform-binding.c:82:30: error: expected ';', ',' or
    ')' before 'int'
       82 |  pid_t * pid,  int  * stdin, int  * stdout, int * stderr)
          |                              ^~~

This commit renames {stdin,stdout,stderr} to
{stdinput,stdoutput,stderror} to avoid colliding with the macros.  The
names I chose aren't great, but they work and I don't have a better
idea.